<?php

namespace Zicht\Bundle\VersioningBundle\Entity\Test;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    public function findById($id)
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.testingId = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
